import {
  archiveAutomationRule,
  cancelAutomationTimer,
  createAutomationTimer,
  dueAutomationTimers,
  deleteAutomationVariable,
  getAutomationRule,
  getAutomationTimer,
  getAutomationVariable,
  incrementAutomationVariable,
  listAutomationRules,
  listAutomationRuns,
  listAutomationTimers,
  listAutomationVariables,
  markAutomationTimerFired,
  pauseAutomationTimer,
  pruneAutomationOperationalHistory,
  recentEvents,
  recentAutomationValueChanges,
  recordAutomationRun,
  recordAutomationValueChange,
  rescheduleAutomationTimer,
  resumeAutomationTimer,
  saveAutomationRule,
  setAutomationRuleEnabled,
  setAutomationVariable,
  snoozeAutomationTimer,
  updateAutomationRuleEvaluation,
} from '../db.js';

export const DEFAULT_STORE = {
  archiveRule: archiveAutomationRule,
  cancelTimer: cancelAutomationTimer,
  createTimer: createAutomationTimer,
  dueTimers: dueAutomationTimers,
  deleteVariable: deleteAutomationVariable,
  getRule: getAutomationRule,
  getTimer: getAutomationTimer,
  getVariable: getAutomationVariable,
  incrementVariable: incrementAutomationVariable,
  listRules: listAutomationRules,
  listRuns: listAutomationRuns,
  listTimers: listAutomationTimers,
  listVariables: listAutomationVariables,
  markTimerFired: markAutomationTimerFired,
  pauseTimer: pauseAutomationTimer,
  prune: pruneAutomationOperationalHistory,
  recentEvents,
  recentValueChanges: recentAutomationValueChanges,
  recordValueChange: recordAutomationValueChange,
  recordRun: recordAutomationRun,
  resumeTimer: resumeAutomationTimer,
  rescheduleTimer: rescheduleAutomationTimer,
  saveRule: saveAutomationRule,
  setRuleEnabled: setAutomationRuleEnabled,
  setVariable: setAutomationVariable,
  snoozeTimer: snoozeAutomationTimer,
  updateEvaluation: updateAutomationRuleEvaluation,
};
