// Model controls follow integration field schemas; disabled integrations stay hidden.
const shared = {
  'assistant-engine': 'Main assistant uses the model selected above.',
  protocols: 'Creating routines uses the main assistant model. Timers and saved routines run without model calls.',
  'even-realities': 'Conversation and widgets use the main assistant. Speech recognition uses Voice input & chat when enabled.',
  'physical-carvis': 'Conversation uses the main assistant. Audio is handled by your enabled voice integrations.',
  'apple-tv': 'Navigation planning runs on your Apple TV AI controller. Its model is configured on that controller.',
  speech: 'Speech is generated by your configured voice service; Home Assistant voices are configured in Home Assistant.',
};
export function modelRouterEntries(integrations) {
  return integrations.filter(i => i.enabled).map(integration => ({
    integration,
    fields: (integration.fields || []).filter(f => f.type !== 'password' && (f.key === 'model' || f.key.endsWith('__model'))),
    note: shared[integration.id] || '',
  })).filter(entry => entry.fields.length || entry.note);
}
